### PR TITLE
Update to AndroidX

### LINKED ISSUE #17: Update to AndroidX
As the support the old Android support libs are going to be stopped, it is now required to update the package to use AndroidX.

All the official first-party plugins are already migrated to AndroidX support libs by the Flutter team.

### PR DESCRIPTION
**Pull request by kdy1**
Fixes #17

### CODE REVIEW

**Comment by yiss** [comment]
I read your pull request and I approve it. @YoussefKababe can you please merge this. Thank you 🙏

**Comment by YoussefKababe** [comment]
Thanks @kdy1 and @yiss

**Comment by kdy1** [comment]
@YoussefKababe Can you release a new version?

**Comment by YoussefKababe** [comment]
New versions published `0.2.0` 🎉

**Pull request merged**
